### ISSUE TITLE
Atom allows to create duplicate users

### ISSUE THREAD

**Issue by amayita** [artefactual-labs/ansible-atom#104]
Expected behavior: No duplicate users are created in Atom by running a playbook several times.

This is probably an Atom issue, but it wouldn't hurt to have  a check here too.
The CLI command to create atom users allows the creation of duplicate users, so a check needs to be added that the users do not exist before creating them.

Client conf `sites/client.yml`:

```  
atom_extra_superusers:
  - email: dip-upload@xxxx.archivematica.org
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64323964613835366531623430346136383461373032313533626136616662383639616461623962
      6230623664306634343836303030316334323536326337370a303966616165653462363337303437
      32383830623066633164356235303632616262323835313630346234653433333734363635623438
      6638353732343064330a313363303836623032636535646534333937333562346639386136323062
      3237
    username: dip-upload
```  

"Bug" is in `artefactual.atom/tasks/flush.yml`
```  
- name: "Add extra super users"
  shell: "php symfony tools:add-superuser --email='{{ item.email }}' --password='{{ item.password }}' {{ item.username }}"
  args:
    chdir: "{{ atom_path }}/{{ atom_extra_path }}"
  when: "atom_extra_superusers is defined"
  with_items: "{{ atom_extra_superusers }}"
```  
Thanks!
