### ISSUE TITLE
Problem: Read-only settings needs 2 variable changes

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-atom#81]
Right now to set a site as read-only we need to change the `atom_pool_php_envs`list and `atom_app_read_only` variable:

```
atom_app_read_only: true   <-- HERE

atom_pool_php_envs:
  ATOM_DEBUG_IP: "127.0.0.1"
  ATOM_READ_ONLY: "on"   <-- HERE
  
```

The `ATOM_READ_ONLY` item should be related to `atom_app_read_only` variable

See: https://www.accesstomemory.org/en/docs/2.6/admin-manual/security/application/#making-atom-read-only
